[package]
name = "almostrusty"
version = "0.1.0"
authors = ["almostbearded"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.20.0"
glutin = "0.22.1"